name: critical_test
version: 8.3.0
homepage: https://www.noojee.dev
documentation: https://criticaltest.noojee.dev
description: Critical Test is a cli tool designed to simplify the process of fixing broken unit tests in Dart.
repository: https://github.com/bsutton/critical_tester

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  args: ^2.4.1
  dcli: ^8.2.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  settings_yaml: ^8.1.0
dev_dependencies:
  build_runner: ^2.2.0
  lint_hard: ^6.2.1
  test: ^1.0.0
  test_api: ^0.7.3
  test_core: ^0.6.5
executables:
  critical_test:
  ct: critical_test
